name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    tags:
    - "v*.*.*"

jobs:
  build-deploy:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.19.5'
    - name: Build
      run: |
        go version
        make build-all
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: _releases/*
